import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import type { Calculation, Dataset } from '../src/api/client'

async function recommendations(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Получить рекомендации' }).click()
  await expect(page.getByRole('checkbox', { name: 'Выбрать DEMO-001', exact: true })).toBeVisible()
}
async function order(page: Page) {
  await recommendations(page)
  await page.getByRole('button', { name: 'Создать черновик' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Количество DEMO-001' })).toBeVisible()
}
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
}
test('поиск, фильтры, ноль, неизвестное количество и сохранение выбора', async ({ page }) => {
  await recommendations(page)
  await expect(page.getByText('144 шт', { exact: true })).toBeVisible()
  await expect(page.getByText('Заказывать не нужно', { exact: true })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Выбрать DEMO-003' })).toBeDisabled()
  await page.getByRole('searchbox', { name: 'Поиск' }).fill('SYN-002')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.getByText('Выбрано: 2 · вне текущей страницы: 1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click()
  await page.getByRole('combobox', { name: 'Срочность', exact: true }).selectOption('needs_input')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('Проблемы данных').selectOption('blocking')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click()
  await page.getByRole('combobox', { name: 'Категория', exact: true }).selectOption('DEMO')
  await page.getByRole('combobox', { name: 'Поставщик', exact: true }).selectOption('demo')
  await expect(page.locator('tbody tr')).toHaveCount(3)
  await page.getByLabel('Сортировка').selectOption('quantity_asc')
  await expect(page.locator('tbody tr').first()).toContainText('DEMO-002')
  await expect(page.locator('tbody tr').last()).toContainText('DEMO-003')
  await page.getByRole('button', { name: 'Очистить выбор' }).click()
  await expect(page.getByRole('button', { name: 'Создать черновик' })).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Выбрать все на текущей странице' }).check()
  await expect(page.getByText('Выбрано: 2', { exact: true })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Поиск' }).fill('несуществующий товар')
  await expect(page.getByRole('heading', { name: 'Товары не найдены' })).toBeVisible()
  await expect(page.getByText('Выбрано: 2 · вне текущей страницы: 2', { exact: true })).toBeVisible()
})

test('панель: поля контракта, клавиатура, фокус, устаревший ответ', async ({ page }) => {
  await recommendations(page)
  const trigger = page.getByRole('button', { name: 'Объяснение DEMO-001' })
  await trigger.click()
  const panel = page.getByRole('dialog')
  await expect(panel.getByText('Потребность до округления', { exact: true })).toBeVisible()
  await expect(panel.getByText('Минимальная отгрузка', { exact: true })).toBeVisible()
  await expect(panel.getByText('Кратность упаковки', { exact: true })).toBeVisible()
  await panel.getByRole('img', { name: 'История спроса, шт' }).scrollIntoViewIfNeeded()
  await expect(panel.getByText('Исходный спрос', { exact: true })).toBeVisible()
  await page.keyboard.press('Tab')
  expect(await page.evaluate(() => !!document.activeElement?.closest('[role=dialog]'))).toBe(true)
  await page.keyboard.press('Shift+Tab')
  expect(await page.evaluate(() => !!document.activeElement?.closest('[role=dialog]'))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await page.route('**/items/demo-item-1', async route => { const response = await route.fetch(); await new Promise(resolve => setTimeout(resolve, 800)); await route.fulfill({ response }) })
  await trigger.click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Объяснение DEMO-002' }).click()
  await expect(panel.getByRole('heading', { name: 'Объяснение: DEMO-002' })).toBeVisible()
  await page.waitForTimeout(1000)
  await expect(panel.getByRole('heading', { name: 'Объяснение: DEMO-002' })).toBeVisible()
})

test('правка: обязательные значения, конфликт 409, явная отмена', async ({ page }) => {
  await order(page)
  const count = page.getByRole('spinbutton', { name: 'Количество DEMO-001' })
  await count.fill('')
  await page.getByRole('button', { name: 'Сохранить правки' }).click()
  await expect(page.getByRole('alert')).toContainText('неотрицательное количество и причину')
  await count.fill('-1')
  await expect(count).toHaveAttribute('aria-invalid', 'true')
  await count.fill('0')
  await page.getByRole('button', { name: 'Сохранить правки' }).click()
  await expect(page.getByRole('alert')).toContainText('причину')
  await page.getByRole('textbox', { name: 'Причина DEMO-001' }).fill('Моя правка')
  await page.route('**/api/orders/*', route => route.request().method() === 'PATCH' ? route.fulfill({ status: 409, json: { error: { code: 'REVISION_CONFLICT', message: 'Заказ уже изменён другим менеджером', details: [] } } }) : route.continue())
  await page.getByRole('button', { name: 'Сохранить правки' }).click()
  await expect(page.getByRole('alert')).toContainText('Версия заказа изменилась')
  await expect(count).toHaveValue('0')
  await expect(page.getByRole('textbox', { name: 'Причина DEMO-001' })).toHaveValue('Моя правка')
  await page.getByRole('button', { name: 'Загрузить актуальную версию' }).click()
  await expect(count).toHaveValue('0')
  await page.getByRole('button', { name: 'Продолжить редактирование' }).click()
  await page.getByRole('button', { name: 'Отменить несохранённые правки' }).click()
  await page.getByRole('button', { name: 'Да, отменить правки' }).click()
  await expect(count).toHaveValue('144')
})

test('CSV: ошибка 409 и сеть остаются внутри интерфейса', async ({ page }) => {
  await order(page)
  await page.getByRole('button', { name: 'Согласовать заказ' }).click()
  await page.route('**/export?*', route => route.fulfill({ status: 409, json: { error: { code: 'REVISION_CONFLICT', message: 'Согласованная версия устарела' } } }))
  await page.getByRole('button', { name: 'Скачать CSV' }).click()
  await expect(page.getByRole('alert')).toContainText('Согласованная версия устарела')
  await expect(page.getByRole('heading', { name: 'Проверка заказа', level: 1 })).toBeVisible()
  await page.unroute('**/export?*')
  await page.route('**/export?*', route => route.abort())
  await page.getByRole('button', { name: 'Скачать CSV' }).click()
  await expect(page.getByRole('alert')).toContainText('Нет соединения')
})

test('импорт: список файлов, лимит, ошибка 501 и детали', async ({ page }) => {
  await page.goto('/')
  const files = page.getByLabel('Книги XLSX')
  await files.setInputFiles({ name: 'wrong.csv', mimeType: 'text/csv', buffer: Buffer.from('test') })
  await expect(page.getByRole('alert')).toContainText('формате XLSX')
  await page.getByRole('button', { name: 'Удалить wrong.csv' }).click()
  await files.setInputFiles({ name: 'large.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.alloc(31 * 1024 * 1024) })
  await expect(page.getByRole('alert')).toContainText('30 МиБ')
  await page.getByRole('button', { name: 'Удалить large.xlsx' }).click()
  await files.setInputFiles([{ name: 'sales.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from('synthetic') }, { name: 'stock.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from('synthetic') }])
  await expect(page.getByText('sales.xlsx', { exact: true })).toBeVisible()
  await expect(page.getByText('stock.xlsx', { exact: true })).toBeVisible()
  await page.route('**/api/datasets', route => route.request().method() === 'POST' ? route.fulfill({ status: 501, json: { error: { code: 'NOT_IMPLEMENTED', message: 'Импорт ещё не подключён', details: [{ code: 'TEST', severity: 'warning', message: 'Проверьте источник', sku: '00012', source: { file: 'sales.xlsx', sheet: 'Продажи', cell: 'A2', row: 2, note: null } }] } } }) : route.continue())
  await page.getByRole('button', { name: 'Загрузить', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Функция пока недоступна')
  await expect(page.getByRole('alert')).toContainText('00012')
  await expect(page.getByRole('alert')).toContainText('Продажи')
  await expect(page.getByRole('heading', { name: 'Данные и настройки', level: 1 })).toBeVisible()
})

test('успешный импорт перечитывает наборы и выбирает новый вне прежнего фильтра', async ({ page }) => {
  const old: Dataset = JSON.parse(await readFile('../contracts/fixtures/dataset.json', 'utf8'))
  const imported: Dataset = { ...old, id: 'import-test', name: 'Новый тестовый набор IEK', suppliers: ['iek'], is_synthetic: false }
  let uploaded = false
  await page.route('**/api/datasets', async route => {
    if (route.request().method() === 'POST') { uploaded = true; await route.fulfill({ json: imported }) }
    else await route.fulfill({ json: uploaded ? [old, imported] : [old] })
  })
  await page.goto('/')
  await page.getByRole('combobox', { name: 'Поставщик набора', exact: true }).selectOption('demo')
  await page.getByRole('combobox', { name: 'Поставщик импорта', exact: true }).selectOption('iek')
  await page.getByLabel('Книги XLSX').setInputFiles({ name: 'iek.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from('synthetic') })
  await page.getByRole('button', { name: 'Загрузить', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Доступные наборы', exact: true })).toHaveValue('import-test')
  await expect(page.getByRole('combobox', { name: 'Поставщик набора', exact: true })).toHaveValue('')
  await expect(page.getByRole('spinbutton', { name: 'Срок поставки Дней до получения заказа' })).toBeEnabled()
})

test('реальные настройки отправляются в API, старые рекомендации помечаются', async ({ page }) => {
  const dataset: Dataset = JSON.parse(await readFile('../contracts/fixtures/dataset.json', 'utf8'))
  dataset.is_synthetic = false
  await page.route('**/api/datasets', route => route.fulfill({ json: [dataset] }))
  await recommendations(page)
  await page.getByRole('button', { name: '1. Данные и настройки' }).click()
  await page.getByLabel('Срок поставки', { exact: false }).fill('20')
  await page.getByLabel('Источник спроса', { exact: false }).selectOption('monthly')
  await page.getByRole('button', { name: '2. Рекомендации' }).click()
  await expect(page.getByRole('status')).toContainText('неактуальны')
  await expect(page.getByRole('button', { name: 'Создать черновик' })).toBeDisabled()
  await page.getByRole('button', { name: '1. Данные и настройки' }).click()
  await page.route('**/api/calculations', async route => {
    expect(route.request().postDataJSON().settings).toMatchObject({ lead_time_days: 20, demand_source: 'monthly' })
    await route.fulfill({ status: 501, json: { error: { code: 'NOT_IMPLEMENTED', message: 'Расчёт ещё не подключён' } } })
  })
  await page.getByRole('button', { name: 'Получить рекомендации' }).click()
  await expect(page.getByRole('alert')).toContainText('Функция пока недоступна')
})

test('тысяча товаров: страницы, один поставщик и сохранённый выбор', async ({ page }) => {
  const fixture: Calculation = JSON.parse(await readFile('../contracts/fixtures/calculation.json', 'utf8'))
  fixture.recommendations = Array.from({ length: 1001 }, (_, i) => ({ ...fixture.recommendations[0], id: `test-${i}`, product: { ...fixture.recommendations[0].product, sku: String(i).padStart(6, '0'), supplier: i % 2 ? 'iek' : 'systeme' } }))
  await page.route('**/api/calculations', route => route.fulfill({ json: fixture }))
  await page.goto('/')
  await page.getByRole('button', { name: 'Получить рекомендации' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(50)
  await page.getByRole('button', { name: 'Очистить выбор' }).click()
  await page.getByRole('checkbox', { name: 'Выбрать 000000', exact: true }).check()
  await expect(page.getByRole('checkbox', { name: 'Выбрать 000001', exact: true })).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Выбрать все на текущей странице' }).check()
  await expect(page.getByText('Выбрано: 25', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Далее', exact: true }).click()
  await expect(page.getByText('Выбрано: 25 · вне текущей страницы: 25', { exact: true })).toBeVisible()
  await page.getByLabel('Строк на странице').selectOption('100')
  await expect(page.locator('tbody tr')).toHaveCount(100)
})

for (const [width, height] of [[1366, 768], [1440, 900], [768, 1024], [390, 844]]) {
  test(`экраны и снимки ${width}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height })
    await page.goto('/')
    await expect(page.getByRole('button', { name: 'Получить рекомендации' })).toBeEnabled()
    await noOverflow(page)
    await page.screenshot({ path: testInfo.outputPath(`data-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Получить рекомендации' }).click()
    await expect(page.getByRole('checkbox', { name: 'Выбрать DEMO-003' })).toBeDisabled()
    await noOverflow(page)
    await page.screenshot({ path: testInfo.outputPath(`recommendations-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: 'Объяснение DEMO-001' }).click()
    await expect(page.getByRole('heading', { name: 'Объяснение: DEMO-001' })).toBeVisible()
    await noOverflow(page)
    await page.screenshot({ path: testInfo.outputPath(`explanation-${width}.png`) })
    await page.getByRole('img', { name: 'История спроса, шт' }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath(`history-${width}.png`) })
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Создать черновик' }).click()
    await expect(page.getByRole('spinbutton', { name: 'Количество DEMO-001' })).toBeVisible()
    await noOverflow(page)
    await page.screenshot({ path: testInfo.outputPath(`order-${width}.png`), fullPage: true })
  })
}
