import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('публичный сайт: настоящий расчёт, настройки, сохранение и CSV', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Попробуйте расчёт' })).toBeVisible({ timeout: 90_000 })
  await expect(page.getByLabel('Книги XLSX')).toHaveCount(0)
  await page.getByLabel('Доступные наборы').selectOption('a-engine-demo-v1')
  await expect(page.getByLabel('Страховой запас', { exact: false })).toBeEnabled()
  await page.getByRole('button', { name: 'Получить рекомендации' }).click()
  await expect(page.getByText('144 шт', { exact: true })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Выбрать SYN-3' })).toBeDisabled()
  await page.getByRole('button', { name: 'Объяснение SYN-1' }).click()
  await expect(page.getByRole('dialog').getByText('Исключено', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть объяснение' }).click()
  await page.getByRole('button', { name: '1. Данные и настройки' }).click()
  await page.getByLabel('Страховой запас', { exact: false }).fill('14')
  await page.getByRole('button', { name: 'Получить рекомендации' }).click()
  await expect(page.getByText('216 шт', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Создать черновик' }).click()
  await page.getByRole('spinbutton', { name: 'Количество SYN-1' }).fill('0')
  await page.getByRole('textbox', { name: 'Причина SYN-1' }).fill('Проверка публичной демонстрации')
  await page.getByRole('button', { name: 'Сохранить правки' }).click()
  await expect(page.getByText('Черновик · версия 2')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('spinbutton', { name: 'Количество SYN-1' })).toHaveValue('0')
  await page.getByRole('button', { name: 'Согласовать заказ' }).click()
  await expect(page.getByText('Согласован · версия 3')).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать CSV' }).click()
  const file = await downloadPromise
  expect((await readFile((await file.path())!)).toString('utf8')).toContain(';216;0;Проверка публичной демонстрации')
  await page.screenshot({ path: testInfo.outputPath('public-approved.png'), fullPage: true })
})
