import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('демо: API → рекомендации → правка → согласование → CSV', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('note')).toContainText('синтетические данные')
  await page.getByRole('button', { name: 'Получить рекомендации' }).click()
  await expect(page.getByRole('checkbox', { name: 'Выбрать DEMO-003' })).toBeDisabled()
  await expect(page.getByRole('checkbox', { name: 'Выбрать DEMO-002' })).toBeChecked()
  await page.getByRole('button', { name: 'Объяснение DEMO-001' }).click()
  await expect(page.getByRole('heading', { name: 'Объяснение: DEMO-001' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('recommendations.png'), fullPage: true })
  await page.getByRole('button', { name: 'Закрыть объяснение' }).click()
  await page.getByRole('button', { name: 'Создать черновик' }).click()
  await page.getByRole('spinbutton', { name: 'Количество DEMO-001' }).fill('0')
  await page.getByRole('textbox', { name: 'Причина DEMO-001' }).fill('Тестовая нулевая правка')
  await expect(page.getByRole('button', { name: 'Согласовать заказ' })).toBeDisabled()
  await expect(page.getByRole('button', { name: '1. Данные и настройки' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Загрузить сохранённый заказ' })).toBeDisabled()
  await page.getByRole('button', { name: 'Сохранить правки' }).click()
  await expect(page.getByText('Черновик · версия 2')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('spinbutton', { name: 'Количество DEMO-001' })).toHaveValue('0')
  await page.getByRole('button', { name: '2. Рекомендации' }).click()
  await expect(page.getByText('144 шт', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '3. Проверка заказа' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Количество DEMO-001' })).toHaveValue('0')
  await page.getByRole('button', { name: 'Согласовать заказ' }).click()
  await expect(page.getByText('Согласован · версия 3')).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать CSV' }).click()
  const download = await downloadPromise
  const contents = await readFile((await download.path())!)
  expect(contents.subarray(0, 3)).toEqual(Buffer.from([239, 187, 191]))
  expect(contents.toString('utf8')).toContain(';144;0;Тестовая нулевая правка')
  await page.screenshot({ path: testInfo.outputPath('approved-order.png'), fullPage: true })
  await page.getByRole('spinbutton', { name: 'Количество DEMO-001' }).fill('12')
  await page.getByRole('button', { name: 'Сохранить правки' }).click()
  await expect(page.getByText('Черновик · версия 4')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Скачать CSV' })).toHaveCount(0)
  const unknown = await page.request.get('/api/no-such-route')
  expect(unknown.status()).toBe(404)
  expect(unknown.headers()['content-type']).toContain('application/json')
  await page.goto('/orders/saved')
  await expect(page.getByRole('heading', { name: 'Проверка заказа', level: 1 })).toBeVisible()
  expect(errors).toEqual([])
})
